version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql  

  app:
    build: .
    environment:
      PYTHONUNBUFFERED: 1  # Force unbuffered output
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 5001  # Port environment variable for Flask
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  postgres_data:
