# docker-compose.yml

version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql  

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: posgres
      DB_USER: admin
      DB_PASSWORD: admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}  
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
